config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show, :destroy]

  resource :session, only: [:new, :create, :destroy]

  resources :bands do 
    resources :albums, only: [:new]
  end 

  resources :albums, only: [:create, :show, :destroy, :update, :edit]
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint           not null, primary key
#  band_id    :integer          not null
#  name       :string           not null
#  year       :date             not null
#  live       :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord 

  validates :name, :year, :band_id, presence: true 
  validates :name, uniqueness: { scope: :band_id }
  validates :live, inclusion: { in: [true, false] }
  validates :year, numericality: { minimum: 1990, maximum: 9000 }

  belongs_to :band 
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord 
  validates :name, presence: true, uniqueness: true
  has_many :albums 
end 

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  attr_reader :password

  validates :email, :password_digest, :session_token,  presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  before_validation :ensure_session_token
  

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)

    user && user.is_password?(password) ? user : nil 
  end 

  def generate_session_token
    SecureRandom.urlsafe_base64(16)
  end 
  
  def reset_session_token!
    self.session_token = generate_session_token
    self.save!
    self.session_token
  end 
  
  def ensure_session_token
    self.session_token ||= generate_session_token
  end 

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
    self.save!
  end 

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end 

end 

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController 
  protect_from_forgery
  
  
  def new 
    @album = Album.new 
    @band = Band.find(params[:band_id])
    render :new
  end 

  def create 
    @album = Album.new(album_params)

    if @album.save
      redirect_to album_url(@album)
    else
      render json: @album.errors.full_messages
    end
  end 

  def show 
    @album = Album.find_by(id: params[:id])
    @band = Band.find_by(id: params[:band_id])
  end 

  def edit 
    @album = Album.find_by(id: params[:id])
    render :edit
  end 

  def update 
    @album = Album.find_by(id: params[:id])
  end 

  def destroy 
  end 

  private 

  def album_params 
    params.require(:album).permit(:name, :year, :live, :band_id)
  end 
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?


  def current_user 
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by(session_token: session[:session_token])
  end 

  def logged_in? 
    !@current_user.nil?
  end 

  def log_in_user!(user)
    @current_user = user 
    session[:session_token] = user.reset_session_token!
  end 

  def logout!
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end 
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController 
  protect_from_forgery
  
  def index 
    @user = current_user
  end 



  def new 
    @band = Band.new 
    render :new 
  end 

  def create 
    @band = Band.new(band_params)

    if @band.save
      redirect_to bands_url
    else 
      render json: @band.errors.full_messages
    end 

  end 

  def show 
    @band = Band.find_by(id: params[:id])
    @albums = albums
    render :show
  end 

  def destroy 
    @band = Band.find_by(id: params[:id])
   
   if @band.delete
    redirect_to bands_url
   else 
    render json: @band.errors.full_messages
   end 
  end 

  def edit 
    @band = Band.find_by(id: params[:id])
    
    render :edit
  end 

  def update 
    @band = Band.find_by(id: params[:id])
    @band.update(name: band_params[:name])

   if @band.save!
    redirect_to band_url(@band)
   else 
    render json: @band.errors.full_messages
   end 

  end 

  private 
  def band_params 
    params.require(:band).permit(:name)
  end 

  def albums 
    Album
    .where(band_id: params[:id])
  end 

end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 
  protect_from_forgery

  def new 
    @user = User.new
    render :new
  end 

  def create 
    @user = User.find_by_credentials( 
      params[:user][:email], 
      params[:user][:password]
    )
    if @user
      log_in_user!(@user)

      redirect_to bands_url
    else
      render json: "Not valid credentials"
    end
  end 

  def destroy 
      logout!
      redirect_to new_user_url
  end 

end 

app/controllers/users_controller.rb
class UsersController < ApplicationController 
   protect_from_forgery
  
  
  def new 
    @user = User.new
    render :new
  end 

  def create 
    @user = User.new(user_params)
    
    if @user.save
      log_in_user!(@user)
      redirect_to bands_url
    else
      render json: 'User not valid'
    end

  end 

  def show 
    @user = User.find_by(id: params[:id])
    render :show
  end 

  private 

  def user_params 
    params.require(:user).permit(:email, :password)
  end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token 
    "<input type='hidden'
      name='athenticity_token'
      value='#{form_authenticity_token}'>".html_safe
  end
end

app/views/albums/edit.html.erb
<h2> Edit <%= @album.name %> </h2>

<form action="<%= album_url(@album) %>" method="post">
<input type="hidden" name="_method" value="patch">

  <%= auth_token %>
  
  <label for="album_name">Name</label>
  <input type="text" name="album[name]" value ="<%= @album.name %>"> 
    <br>

  <label for="album_band">Band</label>
  <select name="album[band_id]">
    <% Band.all.each do |band| %>
      <option 
      
      value="<%= band.id %>" <%= "selected" if @band == band %> > 
      
       <%= band.name %> </option>

    <% end %>
  </select> 
    <br>

  <label for="album_live">Live</label>
  <input type="radio" name="album[live]" <%= "checked" if @album.live %>>
  
  <label for="album_studio">Studio</label>
  <input type="radio" name="album[live]" <%= "checked" if !@album.live %>>
    <br>

  <label for="album_year">Year</label>
  <input type="number" name="album[year]" value ="<%= @album.year %>">
    <br>

  <input type="submit" value="Edit Album!">
</form>

app/views/albums/new.html.erb
<h1>New <%= @band.name %> Album</h1>


<form action="<%= albums_url %>" method="post">
  <%= auth_token %>
  
  <label for="album_name">Name</label>
  <input type="text" name="album[name]"> 
    <br>

  <label for="album_band">Band</label>
  <select name="album[band_id]">
    <% Band.all.each do |band| %>
      <option 
      
      value="<%= band.id %>" <%= "selected" if @band == band %> > 
      
       <%= band.name %> </option>

    <% end %>
  </select> 
    <br>

  <label for="album_live">Live</label>
  <input type="radio" name="album[live]" <%= "checked" if @album.live %>>
  
  <label for="album_studio">Studio</label>
  <input type="radio" name="album[live]" <%= "checked" if !@album.live %>>
    <br>

  <label for="album_year">Year</label>
  <input type="number" name="album[year]">
    <br>

  <input type="submit" value="Create Album!">
</form>

app/views/albums/show.html.erb
<h1> <%= @album.name %>  </h1>



<%= content_for :footer do %>

  <form > 
  <input type="submit" value="New Track">
  </form>

  <form action="<%= edit_album_url(@album) %>"> 
  <input type="submit" value="Edit Album">
  </form>

  <form action="<%= album_url(@album) %>" method="post">
    <input type="hidden" name="_method" value="delete">
    <%= auth_token %>
    <input type='submit' value='Delete Album'>
  </form>

  <form action="<%= band_url(@album.band_id) %>"> 
  <input type="submit" value="Back to Band ">
  </form>

<% end %>

app/views/bands/edit.html.erb
<h3>Edit <%= @band.name %></h3>

<form action="<%= band_url(@band) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  
  <%= auth_token %>

  <label for='band_name'>Band Name:</label> <br>

  <input type='text' name='band[name]' value="<%= @band.name %>"><br>

  <input type='submit' value='Submit'>
</form>

app/views/bands/index.html.erb
<h2>Bands</h2>


<% Band.all.each do |band| %>

<form action="<%= band_url(band) %>">
<input type='submit' value="<%= band.name %>"> 
</form>


<% end %>

<% content_for :footer do %>
  <p>Links<p>
  <form action="<%= new_band_url %>">
  <input type ='submit' value="New Band">
  </form>
<% end %>

app/views/bands/new.html.erb
<h3>Put in a new band!</h3>

<form action="<%= bands_url %>" method="post">
  <%= auth_token %>
  <label for='band_name'>Band Name:</label> <br>

  <input type='text' name='band[name]'><br>

  <input type='submit'>
</form>

app/views/bands/show.html.erb
<h2> <%= @band.name %> </h2>


<h3>Albums</h3>
<% @albums.each do |album| %>
  <form action="<%= album_url(album) %>">
   <input type="submit" value="<%= album.name %>" >
  </form>
<% end %>

<br>


<%= content_for :footer do %>

  <form action="<%= new_band_album_url(@band) %>"> 
  <input type="submit" value="New Album">
  </form>

  <form action="<%= edit_band_url(@band) %>"> 
  <input type="submit" value="Edit Band">
  </form>

  <form action="<%= band_url(@band) %>" method="post">
  <input type="hidden" name="_method" value="delete">
  <%= auth_token %>
  <input type='submit' value='Delete Band'>
  </form>

  <form action="<%= bands_url %>"> 
  <input type="submit" value="All Bands">
  </form>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <h1 class='main-logo'>Musically</h1>

  <% if !current_user.nil? %>

  <div class="logout-button-pos">
  <p> You are currently logged in as <%= current_user.email %>


  <form action='<%= bands_url %>'>
  <input type ="submit" value="Take me Home">
  </form>



  <form action="<%= session_url %>" method="post">

    <input type="hidden"
            name="authenticity_token"
            value="<%= form_authenticity_token %>">

    <input type='hidden' name="_method" value="delete">
    <input type='submit' value="Sign Out" class="logout-button">
  </div>



  </form>
  
  <% end %>
  <body class='body'>
    <%= yield %>


    <footer>
      <%= yield :footer %>
    </footer>
  </body>
</html>

app/views/users/new.html.erb
<form action=" <%= new_session_url %> ">
<input type='submit' value="Go to login">
</form>

<h1 class="signup-header">New User</h1>
<form   action="<%= users_url %>" method='post'>
<%= auth_token %>

<label for='user_email' class="new-user-email">Email:</label>
<input type="text" name='user[email]' id='user_email' class="new-user-email-entry">
<br>
<label for='user_password' class="new-user-password" >Password:</label>
<input type="password" name='user[password]' id='user_password' class="new-user-password-entry">
<br>
  <div class='button'>
<input type='submit' class='button'>
  </div>
</form>

app/views/users/show.html.erb
<h1>Welcome to Musically! <%= @user.email %></h1>